/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardApplicationRouteImport } from './routes/dashboard/application'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPeriodsRouteImport } from './routes/admin/periods'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApplicationRoute = DashboardApplicationRouteImport.update({
  id: '/dashboard/application',
  path: '/dashboard/application',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeriodsRoute = AdminPeriodsRouteImport.update({
  id: '/admin/periods',
  path: '/admin/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/application': typeof DashboardApplicationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/application': typeof DashboardApplicationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/application': typeof DashboardApplicationRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/faq'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/departments'
    | '/admin/periods'
    | '/admin/users'
    | '/dashboard/application'
    | '/dashboard/notifications'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/faq'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/departments'
    | '/admin/periods'
    | '/admin/users'
    | '/dashboard/application'
    | '/dashboard/notifications'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/faq'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/departments'
    | '/admin/periods'
    | '/admin/users'
    | '/dashboard/application'
    | '/dashboard/notifications'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminPeriodsRoute: typeof AdminPeriodsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardApplicationRoute: typeof DashboardApplicationRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/application': {
      id: '/dashboard/application'
      path: '/dashboard/application'
      fullPath: '/dashboard/application'
      preLoaderRoute: typeof DashboardApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/periods': {
      id: '/admin/periods'
      path: '/admin/periods'
      fullPath: '/admin/periods'
      preLoaderRoute: typeof AdminPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminPeriodsRoute: AdminPeriodsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardApplicationRoute: DashboardApplicationRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
